// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyShareURL():Promise<string>;

export function GenerateQRCode():Promise<string>;

export function GetLocalIP():Promise<string>;

export function GetShareDir():Promise<string>;

export function GetShareURL():Promise<string>;

export function IsSharing():Promise<boolean>;

export function OpenInBrowser():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetShareDir(arg1:string):Promise<void>;

export function StartSharing():Promise<string>;

export function StopSharing():Promise<string>;

export function UploadFile():Promise<string>;

export function UploadFilesByPath(arg1:Array<string>):Promise<string>;
