// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyShareURL() {
  return window['go']['main']['App']['CopyShareURL']();
}

export function GenerateQRCode() {
  return window['go']['main']['App']['GenerateQRCode']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetShareDir() {
  return window['go']['main']['App']['GetShareDir']();
}

export function GetShareURL() {
  return window['go']['main']['App']['GetShareURL']();
}

export function IsSharing() {
  return window['go']['main']['App']['IsSharing']();
}

export function OpenInBrowser() {
  return window['go']['main']['App']['OpenInBrowser']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetShareDir(arg1) {
  return window['go']['main']['App']['SetShareDir'](arg1);
}

export function StartSharing() {
  return window['go']['main']['App']['StartSharing']();
}

export function StopSharing() {
  return window['go']['main']['App']['StopSharing']();
}

export function UploadFile() {
  return window['go']['main']['App']['UploadFile']();
}

export function UploadFilesByPath(arg1) {
  return window['go']['main']['App']['UploadFilesByPath'](arg1);
}
